# Generated by Django 5.2.6 on 2026-10-01 00:55

import django.db.models.deletion
import django.utils.timezone
import question_bank.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('theorem', '定理'), ('definition', '定义'), ('lemma', '引理'), ('criterion', '判别法'), ('formula', '公式'), ('other', '其他')], max_length=20)),
                ('formal_statement', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('proof', models.TextField(blank=True)),
                ('usage_signals', models.TextField(blank=True)),
                ('common_mistakes', models.TextField(blank=True)),
                ('personal_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['subject_id', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCardPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_edges', to='question_bank.knowledgecard')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_edges', to='question_bank.knowledgecard')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='prerequisite_cards',
            field=models.ManyToManyField(blank=True, related_name='dependent_cards', through='question_bank.KnowledgeCardPrerequisite', to='question_bank.knowledgecard'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('statement', models.TextField(blank=True)),
                ('personal_solution', models.TextField(blank=True)),
                ('reference_solution', models.TextField(blank=True)),
                ('error_note', models.TextField(blank=True)),
                ('mastery', models.CharField(choices=[('unstarted', '未开始'), ('struggling', '有思路但无法完成'), ('unstable', '可以完成但不稳定'), ('mastered', '熟练掌握')], default='unstarted', max_length=20)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge_cards', models.ManyToManyField(blank=True, related_name='questions', to='question_bank.knowledgecard')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_bank.section')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=question_bank.models.question_attachment_upload_to)),
                ('file_kind', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('other', '其他')], default='image', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='question_bank.question')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('not_done', '未完成'), ('hinted', '看提示完成'), ('independent', '独立完成'), ('mastered', '熟练完成'), ('skipped', '跳过')], max_length=20)),
                ('mastery_before', models.CharField(choices=[('unstarted', '未开始'), ('struggling', '有思路但无法完成'), ('unstable', '可以完成但不稳定'), ('mastered', '熟练掌握')], max_length=20)),
                ('mastery_after', models.CharField(choices=[('unstarted', '未开始'), ('struggling', '有思路但无法完成'), ('unstable', '可以完成但不稳定'), ('mastered', '熟练掌握')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='question_bank.question')),
            ],
            options={
                'ordering': ['-reviewed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_cards', to='question_bank.section'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['name'], name='question_ba_name_c43a9c_idx')],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='question_bank.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='question_bank.subject'),
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_cards', to='question_bank.subject'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('custom', '自定义'), ('method', '方法'), ('problem_type', '题型'), ('source', '来源'), ('error_type', '错误类型'), ('system', '系统')], default='custom', max_length=30)),
                ('archived', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='question_bank.tag')),
                ('redirect_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_sources', to='question_bank.tag')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='question_bank.tag'),
        ),
        migrations.AddIndex(
            model_name='knowledgecardprerequisite',
            index=models.Index(fields=['knowledge_card'], name='question_ba_knowled_e5ee85_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecardprerequisite',
            index=models.Index(fields=['prerequisite'], name='question_ba_prerequ_042eae_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecardprerequisite',
            constraint=models.UniqueConstraint(fields=('knowledge_card', 'prerequisite'), name='unique_knowledge_card_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecardprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('knowledge_card', models.F('prerequisite')), _negated=True), name='knowledge_card_prerequisite_not_self'),
        ),
        migrations.AddIndex(
            model_name='questionattachment',
            index=models.Index(fields=['question', 'sort_order'], name='question_ba_questio_626b90_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionattachment',
            constraint=models.UniqueConstraint(fields=('question', 'sort_order'), name='unique_attachment_order_per_question'),
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['question', '-reviewed_at'], name='question_ba_questio_5dee3f_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['result', '-reviewed_at'], name='question_ba_result_aee924_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['next_review_at'], name='question_ba_next_re_e14b27_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['subject', 'sort_order'], name='question_ba_subject_de6da3_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name'], name='question_ba_name_a81277_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='unique_section_name_per_subject'),
        ),
        migrations.AddIndex(
            model_name='knowledgecard',
            index=models.Index(fields=['subject', 'section'], name='question_ba_subject_9430ea_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecard',
            index=models.Index(fields=['type'], name='question_ba_type_65d9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecard',
            index=models.Index(fields=['name'], name='question_ba_name_5fddae_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['parent', 'name'], name='question_ba_parent__758ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['kind', 'archived'], name='question_ba_kind_ed8c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['redirect_to'], name='question_ba_redirec_512f7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_tag_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_root_tag_name'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'section'], name='question_ba_subject_1a9670_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['mastery', 'next_review_at'], name='question_ba_mastery_6bde7c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['archived', 'draft'], name='question_ba_archive_594f45_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['deleted_at'], name='question_ba_deleted_306dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-updated_at'], name='question_ba_updated_986af6_idx'),
        ),
    ]
