# Generated by Django 5.2.6 on 2026-10-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["archived", "redirect_to", "name"],
                name="tag_picker_prefix_idx",
            ),
        ),
    ]
