# Generated by Django 5.2.6 on 2026-10-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_tag_picker_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecard',
            name='core_content',
            field=models.TextField(blank=True),
        ),
    ]
