# Generated by Django 5.2.6 on 2026-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0004_knowledgecard_type_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='questionattachment',
            name='client_upload_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='questionattachment',
            name='content_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
