# Generated by Django 5.2.6 on 2026-10-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0005_question_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattachment',
            name='attachment_role',
            field=models.CharField(choices=[('question', '题目图片'), ('solution', '解答图片')], default='question', max_length=20),
        ),
    ]
