# Generated by Django 5.2.6 on 2026-10-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0006_questionattachment_attachment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_status',
            field=models.CharField(choices=[('pending', '待分析'), ('analyzing', '分析中'), ('awaiting_review', '待审核'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='personal_signals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='recognized_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='recognized_statement',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='QuestionAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', '待分析'), ('analyzing', '分析中'), ('awaiting_review', '待审核'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=30)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('recognized_statement', models.TextField(blank=True)),
                ('recognized_solution', models.TextField(blank=True)),
                ('knowledge_points', models.JSONField(default=dict)),
                ('suggested_tags', models.JSONField(default=dict)),
                ('missing_cards', models.JSONField(default=dict)),
                ('raw_response', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='question_bank.question')),
            ],
            options={
                'ordering': ['-version', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAIAnalysisAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('confirm', '确认'), ('ignore', '忽略'), ('revoke', '撤销'), ('edit', '编辑')], max_length=20)),
                ('candidate_type', models.CharField(choices=[('knowledge_point', '知识点'), ('tag', '标签'), ('missing_card', '待建立卡片')], max_length=30)),
                ('candidate_key', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='question_bank.questionaianalysis')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='questionaianalysis',
            index=models.Index(fields=['question', '-version'], name='question_ba_questio_afd739_idx'),
        ),
        migrations.AddIndex(
            model_name='questionaianalysis',
            index=models.Index(fields=['status', '-created_at'], name='question_ba_status_864f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='questionaianalysis',
            index=models.Index(fields=['input_fingerprint'], name='question_ba_input_f_11cfc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionaianalysis',
            constraint=models.UniqueConstraint(fields=('question', 'version'), name='unique_question_ai_analysis_version'),
        ),
        migrations.AddIndex(
            model_name='questionaianalysisaction',
            index=models.Index(fields=['analysis', 'candidate_type', 'candidate_key'], name='question_ba_analysi_644329_idx'),
        ),
        migrations.AddIndex(
            model_name='questionaianalysisaction',
            index=models.Index(fields=['action_type', '-created_at'], name='question_ba_action__e9ca19_idx'),
        ),
    ]
