# Generated by Django 5.2.6 on 2026-10-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0007_question_ai_status_question_personal_signals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingKnowledgeCardSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(default='other', max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待建立'), ('dismissed', '已忽略'), ('converted', '已建立')], default='pending', max_length=20)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_card_suggestions', to='question_bank.questionaianalysis')),
                ('created_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestions', to='question_bank.knowledgecard')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='question_ba_status_d7acb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('analysis', 'candidate_key'), name='unique_missing_card_suggestion_candidate')],
            },
        ),
        migrations.AddConstraint(
            model_name='questionaianalysisaction',
            constraint=models.UniqueConstraint(fields=('analysis', 'action_type', 'candidate_type', 'candidate_key'), name='unique_ai_analysis_candidate_action'),
        ),
    ]
