# Generated by Django 5.2.6 on 2026-10-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0008_missingknowledgecardsuggestion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_root_tag_name',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name', 'kind'), name='unique_root_tag_name_per_kind'),
        ),
    ]
