# Generated by Django 5.2.6 on 2026-10-07 11:53

import django.db.models.deletion
from django.db import migrations, models
import uuid


def backfill_review_ownerships(apps, schema_editor):
    Action = apps.get_model('question_bank', 'QuestionAIAnalysisAction')
    Ownership = apps.get_model('question_bank', 'AIReviewOwnership')
    Tag = apps.get_model('question_bank', 'Tag')
    Question = apps.get_model('question_bank', 'Question')
    tag_kinds = {'topic': 'problem_type', 'method': 'method', 'signal': 'custom'}
    tag_through = Question.tags.through
    card_through = Question.knowledge_cards.through
    latest_by_target = {}
    actions = Action.objects.filter(action_type='confirm').select_related('analysis').order_by(
        'updated_at', 'id'
    )
    for action in actions:
        payload = action.payload if isinstance(action.payload, dict) else {}
        if action.candidate_type == 'knowledge_point':
            target_type = 'knowledge_point'
            target_value = payload.get('knowledge_card_id') or action.candidate_key
        elif action.candidate_type == 'tag':
            target_type = 'tag'
            target_value = payload.get('tag_id')
            if not target_value:
                candidate = payload.get('candidate') if isinstance(payload.get('candidate'), dict) else {}
                name = ' '.join(str(candidate.get('name') or '').split())
                kind = tag_kinds.get(candidate.get('category'))
                matches = [
                    tag for tag in Tag.objects.filter(parent__isnull=True, kind=kind)
                    if tag.name.casefold() == name.casefold()
                ] if name and kind else []
                if len(matches) == 1:
                    target_value = matches[0].pk
                    payload['tag_id'] = str(target_value)
                    action.payload = payload
                    action.save(update_fields=['payload'])
                else:
                    payload['ownership_backfill_error'] = (
                        'tag_target_ambiguous' if len(matches) > 1 else 'tag_target_unavailable'
                    )
                    action.payload = payload
                    action.save(update_fields=['payload'])
                    continue
        else:
            continue
        try:
            target_id = uuid.UUID(str(target_value))
        except (TypeError, ValueError, AttributeError):
            payload['ownership_backfill_error'] = 'target_id_unavailable'
            action.payload = payload
            action.save(update_fields=['payload'])
            continue
        latest_by_target[(action.analysis.question_id, target_type, target_id)] = (
            action,
            payload.get('relation_owned', payload.get('relation_added')) is True,
        )

    for (question_id, target_type, target_id), (action, relation_owned) in latest_by_target.items():
        if not relation_owned:
            continue
        relation_exists = (
            card_through.objects.filter(
                question_id=question_id, knowledgecard_id=target_id
            ).exists()
            if target_type == 'knowledge_point'
            else tag_through.objects.filter(question_id=question_id, tag_id=target_id).exists()
        )
        if not relation_exists:
            payload = action.payload if isinstance(action.payload, dict) else {}
            payload['ownership_backfill_error'] = 'relation_missing'
            action.payload = payload
            action.save(update_fields=['payload'])
            continue
        Ownership.objects.update_or_create(
            question_id=question_id,
            target_type=target_type,
            target_id=target_id,
            defaults={'owning_analysis_id': action.analysis_id, 'active': True},
        )


def clear_review_ownerships(apps, schema_editor):
    apps.get_model('question_bank', 'AIReviewOwnership').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_remove_tag_unique_root_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReviewOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('knowledge_point', '知识卡片关联'), ('tag', '标签关联')], max_length=30)),
                ('target_id', models.UUIDField()),
                ('active', models.BooleanField(default=True)),
                ('owning_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_relations', to='question_bank.questionaianalysis')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review_ownerships', to='question_bank.question')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'target_type', 'active'], name='question_ba_questio_90f69a_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'target_type', 'target_id'), name='unique_ai_review_owned_relation')],
            },
        ),
        migrations.RunPython(backfill_review_ownerships, clear_review_ownerships),
    ]
