# Generated by Django 5.2.6 on 2026-10-07 11:53

import django.db.models.deletion
from django.db import migrations, models
import uuid


def backfill_review_ownerships(apps, schema_editor):
    Action = apps.get_model('question_bank', 'QuestionAIAnalysisAction')
    Ownership = apps.get_model('question_bank', 'AIReviewOwnership')
    for action in Action.objects.filter(action_type='confirm').select_related('analysis'):
        payload = action.payload if isinstance(action.payload, dict) else {}
        if payload.get('relation_owned', payload.get('relation_added')) is not True:
            continue
        if action.candidate_type == 'knowledge_point':
            target_type = 'knowledge_point'
            target_value = payload.get('knowledge_card_id') or action.candidate_key
        elif action.candidate_type == 'tag':
            target_type = 'tag'
            target_value = payload.get('tag_id')
        else:
            continue
        try:
            target_id = uuid.UUID(str(target_value))
        except (TypeError, ValueError, AttributeError):
            payload['ownership_backfill_error'] = 'target_id_unavailable'
            action.payload = payload
            action.save(update_fields=['payload'])
            continue
        Ownership.objects.update_or_create(
            question_id=action.analysis.question_id,
            target_type=target_type,
            target_id=target_id,
            defaults={'owning_analysis_id': action.analysis_id, 'active': True},
        )


def clear_review_ownerships(apps, schema_editor):
    apps.get_model('question_bank', 'AIReviewOwnership').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_remove_tag_unique_root_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReviewOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('knowledge_point', '知识卡片关联'), ('tag', '标签关联')], max_length=30)),
                ('target_id', models.UUIDField()),
                ('active', models.BooleanField(default=True)),
                ('owning_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_relations', to='question_bank.questionaianalysis')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review_ownerships', to='question_bank.question')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'target_type', 'active'], name='question_ba_questio_90f69a_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'target_type', 'target_id'), name='unique_ai_review_owned_relation')],
            },
        ),
        migrations.RunPython(backfill_review_ownerships, clear_review_ownerships),
    ]
