# Generated by Django 5.2.6 on 2026-10-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_remove_tag_unique_root_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReviewOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('knowledge_point', '知识卡片关联'), ('tag', '标签关联')], max_length=30)),
                ('target_id', models.UUIDField()),
                ('active', models.BooleanField(default=True)),
                ('owning_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_relations', to='question_bank.questionaianalysis')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review_ownerships', to='question_bank.question')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'target_type', 'active'], name='question_ba_questio_90f69a_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'target_type', 'target_id'), name='unique_ai_review_owned_relation')],
            },
        ),
    ]
